### PR TITLE
fix proptype

### PR DESCRIPTION
**Pull request by gwmccull**

### CODE REVIEW

**Comment by gwmccull** [comment]
@MrDatastorage this is a fix for a bug introduced in the last version. This bug is causing all of my builds to fail so hopefully we can get this merged soon and release a new version

**Comment by bencergazda** [comment]
@MrDatastorage Indeed this fixes the build bug. Should I merge it?

**Comment by Youzhigang** [comment]
it's my fault

**Comment by MrDatastorage** [comment]
Thank you for your contribution to our reborn project.

**Pull request merged**
